# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Azure CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: testdockerneeraj.azurecr.io
        username: ${{ secrets.AzureAppService_ContainerUsername }}  # Secret for the container registry username
        password: ${{ secrets.AzureAppService_ContainerPassword }} # Secret for the container registry password

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: testdockerneeraj.azurecr.io/${{ secrets.AzureAppService_ContainerUsername }}/machinepredictivemaintenance:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'machinepredictivemaintenancecheck'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
        images: 'testdockerneeraj.azurecr.io/${{ secrets.AzureAppService_ContainerUsername }}/machinepredictivemaintenance:${{ github.sha }}'
